title: Nick Ammann
email: ammannnicholas@gmail.com
greeting: Nick Ammann
description: > # 
    Tools Programmer
    
github:  nicholasammann
linkedin: nicholasammann

favicon: favicon.png
# Build settings
paginate: 3
baseurl: "" # the subpath of your site, e.g. /blog/
#baseurl: ""
url: "http://www.nickammann.com" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
gems: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed

# cover images are expected to be 900px by 240px, or at least 15:4 aspect ratio
# thumbnails look best with 3:1 or 5:2 ratios in this layout.
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Nicholas Ammann"
            cover: "/media/homepage_banner.jpg"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Nicholas Ammann"
            cover: "/media/homepage_banner.jpg"
            layout: "default"